spring:
  application:
    name: {{ cookiecutter.project_slug }}
  
  profiles:
    active: dev
  
  {% if cookiecutter.database == 'postgresql' -%}
  datasource:
    url: jdbc:postgresql://localhost:5432/{{ cookiecutter.project_slug.replace('-', '_') }}_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  {% elif cookiecutter.database == 'mysql' -%}
  datasource:
    url: jdbc:mysql://localhost:3306/{{ cookiecutter.project_slug.replace('-', '_') }}_db
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  {% elif cookiecutter.database == 'h2' -%}
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  {% endif -%}
  
  jpa:
    hibernate:
      ddl-auto: {% if cookiecutter.use_flyway == 'true' %}validate{% else %}update{% endif %}
    show-sql: false
    properties:
      hibernate:
        {% if cookiecutter.database == 'postgresql' -%}
        dialect: org.hibernate.dialect.PostgreSQLDialect
        {% elif cookiecutter.database == 'mysql' -%}
        dialect: org.hibernate.dialect.MySQLDialect
        {% elif cookiecutter.database == 'h2' -%}
        dialect: org.hibernate.dialect.H2Dialect
        {% endif -%}
        format_sql: true
  
  {% if cookiecutter.use_flyway == 'true' -%}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  {% endif -%}
  
  {% if cookiecutter.use_security == 'true' -%}
  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:admin123}
      roles: ADMIN
  {% endif %}

server:
  port: {{ cookiecutter.port }}
  servlet:
    context-path: {{ cookiecutter.context_path }}

{% if cookiecutter.use_actuator == 'true' -%}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics{% if cookiecutter.use_actuator == 'true' %},prometheus{% endif %}
  endpoint:
    health:
      show-details: when_authorized
{% endif %}

logging:
  level:
    console: INFO

{% if cookiecutter.use_swagger == 'true' -%}
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
{% endif %}