spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/proddb
    username: produser
    password: prodpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
server:
  port: 8080
logging:
  level:
    root: INFO 